### ISSUE TITLE
Keep all model updates

### ISSUE THREAD

**Issue by rachel3834** [ytsapras/robonet_site#10]
Whenever artemis_subscriber records an updated model to the DB, it should create a new entry in the single_model table, rather than overwrite any existing one.

**Comment by rachel3834** [comment]
The code currently checks to see if the updated timestamp of the ARTEMiS model is more recent than the last_updated timestamp of the most recent single_lens model in the DB.  If the ARTEMiS model is more recent, it adds a new single_lens model to the DB.  

Assigning to Yiannis to confirm that this is the expected behaviour.

**Comment by mpgh** [comment]
Just to be sure, I assume the latest model parameters all come from ARTEMiS.

**Comment by ytsapras** [comment]
TAP needs two things in the database to run: 1) the details from the latest .model file from ARTEMiS (other models can be added to the SingleLens class but TAP should only use the ARTEMiS ones). 2) up-to-date DataFile entries (from the ARTEMiS files) for each event. If for some reason the latest SingleModel and DataFile entries for an event are not in sync with what ARTEMiS provides (e.g. one of the two rsync processes failed to execute), TAP will be not prioritize the targets optimally.

The command to select the latest SingleLens model from ARTEMiS in the database is:
single_recent = SingleModel.objects.select_related().filter(event=event).filter(modeler='ARTEMiS').values().latest('last_updated')

**Comment by rachel3834** [comment]
Yianni, we confirmed today that we fixed this issue, correct?  If so, we can close this issue.

**Comment by ytsapras** [comment]
Yes, the TAP code should (and does) use the latest ARTEMiS model files. Markus can confirm. We may decide to change that to pyLIMA at some future point. It is an easy adjustment.

**Comment by mpgh** [comment]
The latest model parameters come from ARTEMiS. Tests with pyLIMA data basically give us the same selection. The lastest parameters in the db are not used for the time being. In that sense we can close the issue.
