### ISSUE TITLE
REA TAP out of sync

### ISSUE THREAD

**Issue by mpgh** [ytsapras/robonet_site#15]
based on latest ARTEMiS parameters, we should observe fields containing:
OB170926 and KB170305

The first target is on the list albeit with negative magnitude. KB170305 is missing. 

In addition, REA TAP requests on the DB OGLE-2017-BLG-0521/MOA-2017-BLG-0247. That event (is a binary) but more importantly, the last update was on May 9, 2017, 8:09 p.m.

**Comment by mpgh** [comment]
The OB170521 ARTEMiS files are up to date, i.e. there are no newer files on ARTEMiS since May 9, 2017, 8:09 p.m. but that's not what's causing the problem. The PSPL parameters in the database (e.g. tE) don't match what is in the ARTEMiS file.

**Comment by ytsapras** [comment]
I've just copied over the latest version of the database from Einstein to check the problems Markus reports.
For OB170926 the 'latest' parameters from ARTEMiS in the database are not the same as what is reported in the ARTEMiS .model file.

In the database, we have (for OB170926):
single_recent =
{'e_rho': None, 'tau': Decimal('22.1600'), 'last_updated': datetime.datetime(2017, 6, 15, 15, 53, 11, tzinfo=<UTC>), 'e_umin': None, 'tap_omega': None, 'e_pi_e_e': None, u'event_id': 1399, 'Tmax': Decimal('2457920.7047'), 'umin': Decimal('0.2675'), 'chi_sq': None, 'modeler': u'ARTEMiS', 'pi_e_n': None, 'rho': None, 'e_tau': None, 'e_Tmax': None, 'e_pi_e_n': None, u'id': 9509, 'pi_e_e': None}

In the .model file, we have 
[ytsapras@cursa model]$ more OB170926.model
17:51:21.61 -30:05:44.70 OB170926 7918.987333 0.902202 154.450259 35.544690 0.026294 0.006155 1218.639400 849 0
 7916.851370 0

(For reference, the columns in .model are:
1 RA
2 Dec
3 Event
4 t0 (HJD-2450000)
5 t0 err
6 tE
7 tE err
8 u0
9 u0 err
10 chi^2
11 N_data
12 0 
13 timestamp of most recent datapoint)

I don't know why that is the case.

For the second event Markus mentions (KB170305), I could not find an entry in the database.
I run a check for all recorded MOA events and there are several dozens that have no entries. I've attached a list of all MOA events that the database currently 'knows' about. You will see that it misses a large number of events (e.g. MOA-2017-BLG-0205, MOA-2017-BLG-0206, MOA-2017-BLG-0213, MOA-2017-BLG-0218, etc). Somewhere along the line our software is not recording these events in the database. I will look into it next week.

**Comment by rachel3834** [comment]
OB170926/KB170313
Looking at the artemis_subscriber logs, the ARTEMiS .model file contents for this event has been successfully ingested from both of the model files associated with this event:
OB170926.model last updated Jun 12 13:43
KB170313.model last updated Jun 15 08:53

I think the problem in this case is that the KB170313.model file was updated most recently, and the DB event page View lists the parameters from the most recent SingleModel associated with the event...which is the MOA one.  The OGLE model is in the DB, just not being displayed.  TAP, similarly, calls on the most-recent model available.  

Its not clear to me that this is actually the behaviour we want.  Note the last updated timestamp is determined from the time that the model file was last updated on disk i.e. the Unix timestamp.

**Comment by rachel3834** [comment]
The question of events missing from the DB is addressed under issue https://github.com/ytsapras/robonet_site/issues/16

Assigning to Markus for comment.

**Comment by mpgh** [comment]
I am surprised that the model for OGLE and MOA designations of the same event differ. Checking ARTEMiS, that's because ARTEMiS has not identified them as the same event. Due to the better baseline coverage, I would tend to give precedence to OGLE data. That's what the current bypass is doing indirectly. Treating the files as independent events results in the OGLE solution to have higher rank.

**Comment by rachel3834** [comment]
I agree, and I think we should incorporate the OGLE-precedence within the regular code.  I presume this can be done in TAP next week?
