### ISSUE TITLE
Events missing from db

### ISSUE THREAD

**Issue by mpgh** [ytsapras/robonet_site#16]
We are missing some MOA events (e.g. KB170305) which seem to have enough info from ARTEMiS to be requested. Even with the recently commited workaround, we'll still be affected by that issue.

**Comment by rachel3834** [comment]
I've tracked this issue to a misinterpretation of the ARTEMiS .model files.  It is possible for the event name given _in_ the file to be different from the event name in the _name_ of the file.  The subscriber was using only the event name inside the file.  In cases like this one where the event is found by both MOA and OGLE, apparently its the OGLE name that gets quoted inside the file.  

The subscriber was correctly checking to see if the name existed to cross-match the events, but missed that the name of the .model file was different.  I have now corrected this bug and the subscriber will use the name of the .model file to determine the name of the event to be checked.  

Deploying the fix now.

**Comment by rachel3834** [comment]
Fix deployed and verified. Please re-open this issue if you find another occurrence.
