### ISSUE TITLE
Event status parameter not set to active on ingest

### ISSUE THREAD

**Issue by rachel3834** [ytsapras/robonet_site#4]
Bug report from Yiannis:

Looking at the list of events, I noticed a majority that are being added to the database with incorrect status. For example, many events that exist in our fields are tagged as 'NF'=Not in Footprint.

The class Event has the following attributes:

    field -- Field Object 
    	(object, required) -- ForeignKey object
    operator -- Operator object
    	(object, required) -- ForeignKey object
    ev_ra -- Event RA. (string, required)
    ev_dec -- Event DEC. (string, required)
    status -- Events status (string, optional, default='NF')
    		   Available choices: 
    		    'NF':'Not in footprint'
    		    'AC':'active'
    		    'MO':'monitor'
    		    'AN':'anomaly'
    		    'EX':'expired'
    anomaly_rank -- The relative importance of the anomaly. -1 for no anomaly, or 
    						    a positive decimal number. 
    					      (float, optional, default=-1.0)
    year -- Year of discovery. (string, optional, default='')

Note that the field is a required parameter and the status is optional with a default value of 'NF'. This needs to be set to 'AC'=active for each event that is in our footprint. TAP will then set 'MO','EX' (and eventually 'AN') itself.

**Comment by rachel3834** [comment]
Thanks for this bug report - you're right I hadn't appreciated that the default wasn't set to 'AC'.  
I've edited the function I use to sync survey and artemis data with the DB so that it explicitly sets this parameter. 

In the process of doing do, I noticed that the Event.year parameter is supposed to represent the year of discovery of the event, but by default this is set to the current year.  That's a reasonable assumption, but the sync of data from ARTEMiS isn't that specific - events from all available years come through, so this default was resulting in previous-year events being set to 2017 as well.  

I've updated the code to set the event year explicitly from the name of the event - for new events.  However, that may not be what we want for older events.  How do you want to handle this?  

To correct the current contents of the DB, I've implemented the update commands you sent by email as a management command "set_events_to_active", but constrained it so that only 2017 events will be set to active.

**Comment by rachel3834** [comment]
I've run the set_events_to_active command over the active DB on Einstein.  
I noticed a number of events had previously been set to EXpired, and its not clear to me if that was intentional or as a result of a setting inhered from ARTEMiS.  If you would like to set them back to expired, here is the list of affected events (numbers in brackets give event ID PK in DB):
OGLE-2017-BLG-0331 (93), 0186 (248), 0024 (60), 0123 (201), 0023 (24), 0043 (26), 0001 (19), 0025 (20), 0011 (25), 0214 (72), 0005 (50), 0122 (200), 0092 (84), 0171 (235), 0015 (30), 
MOA-2017-BLG-0037 (74)

**Comment by ytsapras** [comment]
> I've updated the code to set the event year explicitly from the name of the event - for new events. However, that may not be what we want for older events. How do you want to handle this?

For older events we can just set the year using the information in the event name. I don't see that creating any problems.

**Comment by ytsapras** [comment]
> a number of events had previously been set to EXpired

TAP should automatically set those to expired again event if you reactivate them.

**Comment by mpgh** [comment]
Currently, TAP does not deactivate events, because it erroneously 
switched events off based on their Tmax.

**Comment by rachel3834** [comment]
OK.  I think this issue can be closed, and if we become aware that some events are still active that should be deactivated, we can do this manually for now.
